################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
C++_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
bindings/python \
build/scratch/mqsim_qtcp_example \
build/scratch/nvmetcp_new \
build/scratch/nvmetcp_new_RTT_Fairness \
build/scratch/nvmetcp_new_RTT_Fairness_Fat_tree \
build/scratch/nvmetcp_new_RTT_Fairness_Fat_tree_trade \
build/scratch/nvmetcp_new_RTT_alpha_check \
build/scratch/nvmetcp_new_latency \
build/scratch/nvmetcp_new_tcp_friendliness_latest \
build/scratch \
build/scratch/subdir \
build/scratch/tompecs_mqsim \
build/scratch/tompecs_mqsim_latency \
build/scratch/tompecs_mqsim_readonly_throughput \
build/scratch/tompecs_mqsim_readonly_throughput_pm \
build/scratch/tompecs_mqsim_readonly_throughput_pm_fattree \
build/scratch/tompecs_mqsim_readwrite_latency \
build/scratch/tompecs_mqsim_readwrite_latency2 \
build/scratch/tompecs_mqsim_readwrite_throughput \
build/scratch/tompecs_mqsim_trace_throughput_pm \
build/scratch/tompecs_mqsim_writeonly_latency_pm \
build/scratch/tompecs_mqsim_writeonly_throughput \
build/scratch/tompecs_mqsim_writeonly_throughput_pm \
build/src/MQsim/helper \
build/src/MQsim/model \
build/src/MQsim/model/exec \
build/src/MQsim/model/host \
build/src/MQsim/model/nvm_chip/flash_memory \
build/src/MQsim/model/sim \
build/src/MQsim/model/ssd \
build/src/MQsim/model/utils \
build/src/antenna/model \
build/src/aodv/helper \
build/src/aodv/model \
build/src/applications/helper \
build/src/applications/model \
build/src/bridge/helper \
build/src/bridge/model \
build/src/buildings/helper \
build/src/buildings/model \
build/src/config-store/model \
build/src/core/helper \
build/src/core/model \
build/src/csma/helper \
build/src/csma/model \
build/src/csma-layout/model \
build/src/dsdv/helper \
build/src/dsdv/model \
build/src/dsr/helper \
build/src/dsr/model \
build/src/energy/helper \
build/src/energy/model \
build/src/fd-net-device/helper \
build/src/fd-net-device/model \
build/src/flow-monitor/helper \
build/src/flow-monitor/model \
build/src/internet/helper \
build/src/internet/model \
build/src/internet-apps/helper \
build/src/internet-apps/model \
build/src/lr-wpan/helper \
build/src/lr-wpan/model \
build/src/lte/helper \
build/src/lte/model \
build/src/mesh/helper/dot11s \
build/src/mesh/helper/flame \
build/src/mesh/helper \
build/src/mesh/model/dot11s \
build/src/mesh/model/flame \
build/src/mesh/model \
build/src/mobility/helper \
build/src/mobility/model \
build/src/netanim/model \
build/src/network/helper \
build/src/network/model \
build/src/network/utils \
build/src/nix-vector-routing/helper \
build/src/nix-vector-routing/model \
build/src/olsr/helper \
build/src/olsr/model \
build/src/point-to-point/helper \
build/src/point-to-point/model \
build/src/point-to-point-layout/model \
build/src/propagation/model \
build/src/sixlowpan/helper \
build/src/sixlowpan/model \
build/src/spectrum/helper \
build/src/spectrum/model \
build/src/stats/helper \
build/src/stats/model \
build/src/tap-bridge/helper \
build/src/tap-bridge/model \
build/src/topology-read/helper \
build/src/topology-read/model \
build/src/traffic-control/helper \
build/src/traffic-control/model \
build/src/uan/helper \
build/src/uan/model \
build/src/virtual-net-device/model \
build/src/wave/helper \
build/src/wave/model \
build/src/wifi/helper \
build/src/wifi/model \
build/src/wimax/helper \
build/src/wimax/model \
build/utils \
examples/channel-models \
examples/energy \
examples/error-model \
examples/ipv6 \
examples/matrix-topology \
examples/naming \
examples/realtime \
examples/routing \
examples/socket \
examples/stats \
examples/tcp \
examples/traffic-control \
examples/tutorial \
examples/udp \
examples/udp-client-server \
examples/wireless \
scratch/mqsim_qtcp_example \
scratch/nvmetcp_new \
scratch/nvmetcp_new_RTT_Fairness \
scratch/nvmetcp_new_RTT_Fairness_Fat_tree \
scratch/nvmetcp_new_RTT_Fairness_Fat_tree_trade \
scratch/nvmetcp_new_RTT_alpha_check \
scratch/nvmetcp_new_latency \
scratch/nvmetcp_new_tcp_friendliness_latest \
scratch \
scratch/subdir \
scratch/tompecs_mqsim_latency \
scratch/tompecs_mqsim_readonly_throughput \
scratch/tompecs_mqsim_readonly_throughput_pm \
scratch/tompecs_mqsim_readonly_throughput_pm_fattree \
scratch/tompecs_mqsim_readwrite_latency \
scratch/tompecs_mqsim_readwrite_latency2 \
scratch/tompecs_mqsim_readwrite_throughput \
scratch/tompecs_mqsim_trace_throughput_pm \
scratch/tompecs_mqsim_writeonly_latency_pm \
scratch/tompecs_mqsim_writeonly_throughput \
scratch/tompecs_mqsim_writeonly_throughput_pm \
src/MQsim/examples \
src/MQsim/helper \
src/MQsim/model \
src/MQsim/model/exec \
src/MQsim/model/host \
src/MQsim/model/nvm_chip/flash_memory \
src/MQsim/model/sim \
src/MQsim/model/ssd \
src/MQsim/model/utils \
src/MQsim/test \
src/antenna/model \
src/antenna/test \
src/aodv/examples \
src/aodv/helper \
src/aodv/model \
src/aodv/test \
src/applications/examples \
src/applications/helper \
src/applications/model \
src/applications/test \
src/bridge/examples \
src/bridge/helper \
src/bridge/model \
src/brite/examples \
src/brite/helper \
src/brite/test \
src/buildings/examples \
src/buildings/helper \
src/buildings/model \
src/buildings/test \
src/click/examples \
src/click/helper \
src/click/model \
src/click/test \
src/config-store/examples \
src/config-store/model \
src/core/bindings \
src/core/examples \
src/core/helper \
src/core/model \
src/core/test \
src/csma/examples \
src/csma/helper \
src/csma/model \
src/csma-layout/examples \
src/csma-layout/model \
src/dsdv/examples \
src/dsdv/helper \
src/dsdv/model \
src/dsdv/test \
src/dsr/examples \
src/dsr/helper \
src/dsr/model \
src/dsr/test \
src/energy/examples \
src/energy/helper \
src/energy/model \
src/energy/test \
src/fd-net-device/examples \
src/fd-net-device/helper \
src/fd-net-device/model \
src/flow-monitor/helper \
src/flow-monitor/model \
src/flow-monitor/test \
src/internet/examples \
src/internet/helper \
src/internet/model \
src/internet/test \
src/internet-apps/examples \
src/internet-apps/helper \
src/internet-apps/model \
src/internet-apps/test \
src/lr-wpan/examples \
src/lr-wpan/helper \
src/lr-wpan/model \
src/lr-wpan/test \
src/lte/examples \
src/lte/helper \
src/lte/model \
src/lte/test \
src/mesh/examples \
src/mesh/helper/dot11s \
src/mesh/helper/flame \
src/mesh/helper \
src/mesh/model/dot11s \
src/mesh/model/flame \
src/mesh/model \
src/mesh/test/dot11s \
src/mesh/test/flame \
src/mesh/test \
src/mobility/examples \
src/mobility/helper \
src/mobility/model \
src/mobility/test \
src/mpi/examples \
src/mpi/model \
src/mpi/test \
src/netanim/examples \
src/netanim/model \
src/netanim/test \
src/network/examples \
src/network/helper \
src/network/model \
src/network/test \
src/network/utils \
src/nix-vector-routing/examples \
src/nix-vector-routing/helper \
src/nix-vector-routing/model \
src/olsr/examples \
src/olsr/helper \
src/olsr/model \
src/olsr/test \
src/openflow/examples \
src/openflow/helper \
src/openflow/model \
src/openflow/test \
src/point-to-point/examples \
src/point-to-point/helper \
src/point-to-point/model \
src/point-to-point/test \
src/point-to-point-layout/model \
src/propagation/examples \
src/propagation/model \
src/propagation/test \
src/sixlowpan/examples \
src/sixlowpan/helper \
src/sixlowpan/model \
src/sixlowpan/test \
src/spectrum/examples \
src/spectrum/helper \
src/spectrum/model \
src/spectrum/test \
src/stats/examples \
src/stats/helper \
src/stats/model \
src/stats/test \
src/tap-bridge/examples \
src/tap-bridge/helper \
src/tap-bridge/model \
src/test \
src/test/ns3tc \
src/test/ns3tcp \
src/test/ns3wifi \
src/test/perf \
src/test/traced \
src/topology-read/examples \
src/topology-read/helper \
src/topology-read/model \
src/topology-read/test \
src/traffic-control/examples \
src/traffic-control/helper \
src/traffic-control/model \
src/traffic-control/test \
src/uan/examples \
src/uan/helper \
src/uan/model \
src/uan/test \
src/virtual-net-device/examples \
src/virtual-net-device/model \
src/visualizer/model \
src/wave/examples \
src/wave/helper \
src/wave/model \
src/wave/test \
src/wifi/examples \
src/wifi/helper \
src/wifi/model \
src/wifi/test \
src/wimax/examples \
src/wimax/helper \
src/wimax/model \
src/wimax/test \
utils \

