################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../src/wifi/model/aarf-wifi-manager.cc \
../src/wifi/model/aarfcd-wifi-manager.cc \
../src/wifi/model/adhoc-wifi-mac.cc \
../src/wifi/model/ampdu-subframe-header.cc \
../src/wifi/model/ampdu-tag.cc \
../src/wifi/model/amrr-wifi-manager.cc \
../src/wifi/model/amsdu-subframe-header.cc \
../src/wifi/model/ap-wifi-mac.cc \
../src/wifi/model/aparf-wifi-manager.cc \
../src/wifi/model/arf-wifi-manager.cc \
../src/wifi/model/block-ack-agreement.cc \
../src/wifi/model/block-ack-cache.cc \
../src/wifi/model/block-ack-manager.cc \
../src/wifi/model/block-ack-window.cc \
../src/wifi/model/capability-information.cc \
../src/wifi/model/cara-wifi-manager.cc \
../src/wifi/model/cf-parameter-set.cc \
../src/wifi/model/channel-access-manager.cc \
../src/wifi/model/constant-obss-pd-algorithm.cc \
../src/wifi/model/constant-rate-wifi-manager.cc \
../src/wifi/model/constant-wifi-ack-policy-selector.cc \
../src/wifi/model/ctrl-headers.cc \
../src/wifi/model/dsss-error-rate-model.cc \
../src/wifi/model/dsss-parameter-set.cc \
../src/wifi/model/edca-parameter-set.cc \
../src/wifi/model/erp-information.cc \
../src/wifi/model/error-rate-model.cc \
../src/wifi/model/extended-capabilities.cc \
../src/wifi/model/frame-capture-model.cc \
../src/wifi/model/he-capabilities.cc \
../src/wifi/model/he-configuration.cc \
../src/wifi/model/he-operation.cc \
../src/wifi/model/he-ru.cc \
../src/wifi/model/ht-capabilities.cc \
../src/wifi/model/ht-configuration.cc \
../src/wifi/model/ht-operation.cc \
../src/wifi/model/ideal-wifi-manager.cc \
../src/wifi/model/infrastructure-wifi-mac.cc \
../src/wifi/model/interference-helper.cc \
../src/wifi/model/mac-low-transmission-parameters.cc \
../src/wifi/model/mac-low.cc \
../src/wifi/model/mac-rx-middle.cc \
../src/wifi/model/mac-tx-middle.cc \
../src/wifi/model/mgt-headers.cc \
../src/wifi/model/minstrel-ht-wifi-manager.cc \
../src/wifi/model/minstrel-wifi-manager.cc \
../src/wifi/model/mpdu-aggregator.cc \
../src/wifi/model/msdu-aggregator.cc \
../src/wifi/model/nist-error-rate-model.cc \
../src/wifi/model/obss-pd-algorithm.cc \
../src/wifi/model/onoe-wifi-manager.cc \
../src/wifi/model/originator-block-ack-agreement.cc \
../src/wifi/model/parf-wifi-manager.cc \
../src/wifi/model/preamble-detection-model.cc \
../src/wifi/model/qos-blocked-destinations.cc \
../src/wifi/model/qos-txop.cc \
../src/wifi/model/qos-utils.cc \
../src/wifi/model/regular-wifi-mac.cc \
../src/wifi/model/rraa-wifi-manager.cc \
../src/wifi/model/rrpaa-wifi-manager.cc \
../src/wifi/model/simple-frame-capture-model.cc \
../src/wifi/model/snr-tag.cc \
../src/wifi/model/spectrum-wifi-phy.cc \
../src/wifi/model/ssid.cc \
../src/wifi/model/sta-wifi-mac.cc \
../src/wifi/model/status-code.cc \
../src/wifi/model/supported-rates.cc \
../src/wifi/model/table-based-error-rate-model.cc \
../src/wifi/model/threshold-preamble-detection-model.cc \
../src/wifi/model/txop.cc \
../src/wifi/model/vht-capabilities.cc \
../src/wifi/model/vht-configuration.cc \
../src/wifi/model/vht-operation.cc \
../src/wifi/model/wifi-ack-policy-selector.cc \
../src/wifi/model/wifi-information-element-vector.cc \
../src/wifi/model/wifi-information-element.cc \
../src/wifi/model/wifi-mac-header.cc \
../src/wifi/model/wifi-mac-queue-item.cc \
../src/wifi/model/wifi-mac-queue.cc \
../src/wifi/model/wifi-mac-trailer.cc \
../src/wifi/model/wifi-mac.cc \
../src/wifi/model/wifi-mode.cc \
../src/wifi/model/wifi-net-device.cc \
../src/wifi/model/wifi-phy-header.cc \
../src/wifi/model/wifi-phy-state-helper.cc \
../src/wifi/model/wifi-phy-tag.cc \
../src/wifi/model/wifi-phy.cc \
../src/wifi/model/wifi-ppdu.cc \
../src/wifi/model/wifi-psdu.cc \
../src/wifi/model/wifi-radio-energy-model.cc \
../src/wifi/model/wifi-remote-station-info.cc \
../src/wifi/model/wifi-remote-station-manager.cc \
../src/wifi/model/wifi-spectrum-phy-interface.cc \
../src/wifi/model/wifi-spectrum-signal-parameters.cc \
../src/wifi/model/wifi-tx-current-model.cc \
../src/wifi/model/wifi-tx-vector.cc \
../src/wifi/model/wifi-utils.cc \
../src/wifi/model/yans-error-rate-model.cc \
../src/wifi/model/yans-wifi-channel.cc \
../src/wifi/model/yans-wifi-phy.cc 

CC_DEPS += \
./src/wifi/model/aarf-wifi-manager.d \
./src/wifi/model/aarfcd-wifi-manager.d \
./src/wifi/model/adhoc-wifi-mac.d \
./src/wifi/model/ampdu-subframe-header.d \
./src/wifi/model/ampdu-tag.d \
./src/wifi/model/amrr-wifi-manager.d \
./src/wifi/model/amsdu-subframe-header.d \
./src/wifi/model/ap-wifi-mac.d \
./src/wifi/model/aparf-wifi-manager.d \
./src/wifi/model/arf-wifi-manager.d \
./src/wifi/model/block-ack-agreement.d \
./src/wifi/model/block-ack-cache.d \
./src/wifi/model/block-ack-manager.d \
./src/wifi/model/block-ack-window.d \
./src/wifi/model/capability-information.d \
./src/wifi/model/cara-wifi-manager.d \
./src/wifi/model/cf-parameter-set.d \
./src/wifi/model/channel-access-manager.d \
./src/wifi/model/constant-obss-pd-algorithm.d \
./src/wifi/model/constant-rate-wifi-manager.d \
./src/wifi/model/constant-wifi-ack-policy-selector.d \
./src/wifi/model/ctrl-headers.d \
./src/wifi/model/dsss-error-rate-model.d \
./src/wifi/model/dsss-parameter-set.d \
./src/wifi/model/edca-parameter-set.d \
./src/wifi/model/erp-information.d \
./src/wifi/model/error-rate-model.d \
./src/wifi/model/extended-capabilities.d \
./src/wifi/model/frame-capture-model.d \
./src/wifi/model/he-capabilities.d \
./src/wifi/model/he-configuration.d \
./src/wifi/model/he-operation.d \
./src/wifi/model/he-ru.d \
./src/wifi/model/ht-capabilities.d \
./src/wifi/model/ht-configuration.d \
./src/wifi/model/ht-operation.d \
./src/wifi/model/ideal-wifi-manager.d \
./src/wifi/model/infrastructure-wifi-mac.d \
./src/wifi/model/interference-helper.d \
./src/wifi/model/mac-low-transmission-parameters.d \
./src/wifi/model/mac-low.d \
./src/wifi/model/mac-rx-middle.d \
./src/wifi/model/mac-tx-middle.d \
./src/wifi/model/mgt-headers.d \
./src/wifi/model/minstrel-ht-wifi-manager.d \
./src/wifi/model/minstrel-wifi-manager.d \
./src/wifi/model/mpdu-aggregator.d \
./src/wifi/model/msdu-aggregator.d \
./src/wifi/model/nist-error-rate-model.d \
./src/wifi/model/obss-pd-algorithm.d \
./src/wifi/model/onoe-wifi-manager.d \
./src/wifi/model/originator-block-ack-agreement.d \
./src/wifi/model/parf-wifi-manager.d \
./src/wifi/model/preamble-detection-model.d \
./src/wifi/model/qos-blocked-destinations.d \
./src/wifi/model/qos-txop.d \
./src/wifi/model/qos-utils.d \
./src/wifi/model/regular-wifi-mac.d \
./src/wifi/model/rraa-wifi-manager.d \
./src/wifi/model/rrpaa-wifi-manager.d \
./src/wifi/model/simple-frame-capture-model.d \
./src/wifi/model/snr-tag.d \
./src/wifi/model/spectrum-wifi-phy.d \
./src/wifi/model/ssid.d \
./src/wifi/model/sta-wifi-mac.d \
./src/wifi/model/status-code.d \
./src/wifi/model/supported-rates.d \
./src/wifi/model/table-based-error-rate-model.d \
./src/wifi/model/threshold-preamble-detection-model.d \
./src/wifi/model/txop.d \
./src/wifi/model/vht-capabilities.d \
./src/wifi/model/vht-configuration.d \
./src/wifi/model/vht-operation.d \
./src/wifi/model/wifi-ack-policy-selector.d \
./src/wifi/model/wifi-information-element-vector.d \
./src/wifi/model/wifi-information-element.d \
./src/wifi/model/wifi-mac-header.d \
./src/wifi/model/wifi-mac-queue-item.d \
./src/wifi/model/wifi-mac-queue.d \
./src/wifi/model/wifi-mac-trailer.d \
./src/wifi/model/wifi-mac.d \
./src/wifi/model/wifi-mode.d \
./src/wifi/model/wifi-net-device.d \
./src/wifi/model/wifi-phy-header.d \
./src/wifi/model/wifi-phy-state-helper.d \
./src/wifi/model/wifi-phy-tag.d \
./src/wifi/model/wifi-phy.d \
./src/wifi/model/wifi-ppdu.d \
./src/wifi/model/wifi-psdu.d \
./src/wifi/model/wifi-radio-energy-model.d \
./src/wifi/model/wifi-remote-station-info.d \
./src/wifi/model/wifi-remote-station-manager.d \
./src/wifi/model/wifi-spectrum-phy-interface.d \
./src/wifi/model/wifi-spectrum-signal-parameters.d \
./src/wifi/model/wifi-tx-current-model.d \
./src/wifi/model/wifi-tx-vector.d \
./src/wifi/model/wifi-utils.d \
./src/wifi/model/yans-error-rate-model.d \
./src/wifi/model/yans-wifi-channel.d \
./src/wifi/model/yans-wifi-phy.d 

OBJS += \
./src/wifi/model/aarf-wifi-manager.o \
./src/wifi/model/aarfcd-wifi-manager.o \
./src/wifi/model/adhoc-wifi-mac.o \
./src/wifi/model/ampdu-subframe-header.o \
./src/wifi/model/ampdu-tag.o \
./src/wifi/model/amrr-wifi-manager.o \
./src/wifi/model/amsdu-subframe-header.o \
./src/wifi/model/ap-wifi-mac.o \
./src/wifi/model/aparf-wifi-manager.o \
./src/wifi/model/arf-wifi-manager.o \
./src/wifi/model/block-ack-agreement.o \
./src/wifi/model/block-ack-cache.o \
./src/wifi/model/block-ack-manager.o \
./src/wifi/model/block-ack-window.o \
./src/wifi/model/capability-information.o \
./src/wifi/model/cara-wifi-manager.o \
./src/wifi/model/cf-parameter-set.o \
./src/wifi/model/channel-access-manager.o \
./src/wifi/model/constant-obss-pd-algorithm.o \
./src/wifi/model/constant-rate-wifi-manager.o \
./src/wifi/model/constant-wifi-ack-policy-selector.o \
./src/wifi/model/ctrl-headers.o \
./src/wifi/model/dsss-error-rate-model.o \
./src/wifi/model/dsss-parameter-set.o \
./src/wifi/model/edca-parameter-set.o \
./src/wifi/model/erp-information.o \
./src/wifi/model/error-rate-model.o \
./src/wifi/model/extended-capabilities.o \
./src/wifi/model/frame-capture-model.o \
./src/wifi/model/he-capabilities.o \
./src/wifi/model/he-configuration.o \
./src/wifi/model/he-operation.o \
./src/wifi/model/he-ru.o \
./src/wifi/model/ht-capabilities.o \
./src/wifi/model/ht-configuration.o \
./src/wifi/model/ht-operation.o \
./src/wifi/model/ideal-wifi-manager.o \
./src/wifi/model/infrastructure-wifi-mac.o \
./src/wifi/model/interference-helper.o \
./src/wifi/model/mac-low-transmission-parameters.o \
./src/wifi/model/mac-low.o \
./src/wifi/model/mac-rx-middle.o \
./src/wifi/model/mac-tx-middle.o \
./src/wifi/model/mgt-headers.o \
./src/wifi/model/minstrel-ht-wifi-manager.o \
./src/wifi/model/minstrel-wifi-manager.o \
./src/wifi/model/mpdu-aggregator.o \
./src/wifi/model/msdu-aggregator.o \
./src/wifi/model/nist-error-rate-model.o \
./src/wifi/model/obss-pd-algorithm.o \
./src/wifi/model/onoe-wifi-manager.o \
./src/wifi/model/originator-block-ack-agreement.o \
./src/wifi/model/parf-wifi-manager.o \
./src/wifi/model/preamble-detection-model.o \
./src/wifi/model/qos-blocked-destinations.o \
./src/wifi/model/qos-txop.o \
./src/wifi/model/qos-utils.o \
./src/wifi/model/regular-wifi-mac.o \
./src/wifi/model/rraa-wifi-manager.o \
./src/wifi/model/rrpaa-wifi-manager.o \
./src/wifi/model/simple-frame-capture-model.o \
./src/wifi/model/snr-tag.o \
./src/wifi/model/spectrum-wifi-phy.o \
./src/wifi/model/ssid.o \
./src/wifi/model/sta-wifi-mac.o \
./src/wifi/model/status-code.o \
./src/wifi/model/supported-rates.o \
./src/wifi/model/table-based-error-rate-model.o \
./src/wifi/model/threshold-preamble-detection-model.o \
./src/wifi/model/txop.o \
./src/wifi/model/vht-capabilities.o \
./src/wifi/model/vht-configuration.o \
./src/wifi/model/vht-operation.o \
./src/wifi/model/wifi-ack-policy-selector.o \
./src/wifi/model/wifi-information-element-vector.o \
./src/wifi/model/wifi-information-element.o \
./src/wifi/model/wifi-mac-header.o \
./src/wifi/model/wifi-mac-queue-item.o \
./src/wifi/model/wifi-mac-queue.o \
./src/wifi/model/wifi-mac-trailer.o \
./src/wifi/model/wifi-mac.o \
./src/wifi/model/wifi-mode.o \
./src/wifi/model/wifi-net-device.o \
./src/wifi/model/wifi-phy-header.o \
./src/wifi/model/wifi-phy-state-helper.o \
./src/wifi/model/wifi-phy-tag.o \
./src/wifi/model/wifi-phy.o \
./src/wifi/model/wifi-ppdu.o \
./src/wifi/model/wifi-psdu.o \
./src/wifi/model/wifi-radio-energy-model.o \
./src/wifi/model/wifi-remote-station-info.o \
./src/wifi/model/wifi-remote-station-manager.o \
./src/wifi/model/wifi-spectrum-phy-interface.o \
./src/wifi/model/wifi-spectrum-signal-parameters.o \
./src/wifi/model/wifi-tx-current-model.o \
./src/wifi/model/wifi-tx-vector.o \
./src/wifi/model/wifi-utils.o \
./src/wifi/model/yans-error-rate-model.o \
./src/wifi/model/yans-wifi-channel.o \
./src/wifi/model/yans-wifi-phy.o 


# Each subdirectory must supply rules for building sources it contributes
src/wifi/model/%.o: ../src/wifi/model/%.cc src/wifi/model/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


clean: clean-src-2f-wifi-2f-model

clean-src-2f-wifi-2f-model:
	-$(RM) ./src/wifi/model/aarf-wifi-manager.d ./src/wifi/model/aarf-wifi-manager.o ./src/wifi/model/aarfcd-wifi-manager.d ./src/wifi/model/aarfcd-wifi-manager.o ./src/wifi/model/adhoc-wifi-mac.d ./src/wifi/model/adhoc-wifi-mac.o ./src/wifi/model/ampdu-subframe-header.d ./src/wifi/model/ampdu-subframe-header.o ./src/wifi/model/ampdu-tag.d ./src/wifi/model/ampdu-tag.o ./src/wifi/model/amrr-wifi-manager.d ./src/wifi/model/amrr-wifi-manager.o ./src/wifi/model/amsdu-subframe-header.d ./src/wifi/model/amsdu-subframe-header.o ./src/wifi/model/ap-wifi-mac.d ./src/wifi/model/ap-wifi-mac.o ./src/wifi/model/aparf-wifi-manager.d ./src/wifi/model/aparf-wifi-manager.o ./src/wifi/model/arf-wifi-manager.d ./src/wifi/model/arf-wifi-manager.o ./src/wifi/model/block-ack-agreement.d ./src/wifi/model/block-ack-agreement.o ./src/wifi/model/block-ack-cache.d ./src/wifi/model/block-ack-cache.o ./src/wifi/model/block-ack-manager.d ./src/wifi/model/block-ack-manager.o ./src/wifi/model/block-ack-window.d ./src/wifi/model/block-ack-window.o ./src/wifi/model/capability-information.d ./src/wifi/model/capability-information.o ./src/wifi/model/cara-wifi-manager.d ./src/wifi/model/cara-wifi-manager.o ./src/wifi/model/cf-parameter-set.d ./src/wifi/model/cf-parameter-set.o ./src/wifi/model/channel-access-manager.d ./src/wifi/model/channel-access-manager.o ./src/wifi/model/constant-obss-pd-algorithm.d ./src/wifi/model/constant-obss-pd-algorithm.o ./src/wifi/model/constant-rate-wifi-manager.d ./src/wifi/model/constant-rate-wifi-manager.o ./src/wifi/model/constant-wifi-ack-policy-selector.d ./src/wifi/model/constant-wifi-ack-policy-selector.o ./src/wifi/model/ctrl-headers.d ./src/wifi/model/ctrl-headers.o ./src/wifi/model/dsss-error-rate-model.d ./src/wifi/model/dsss-error-rate-model.o ./src/wifi/model/dsss-parameter-set.d ./src/wifi/model/dsss-parameter-set.o ./src/wifi/model/edca-parameter-set.d ./src/wifi/model/edca-parameter-set.o ./src/wifi/model/erp-information.d ./src/wifi/model/erp-information.o ./src/wifi/model/error-rate-model.d ./src/wifi/model/error-rate-model.o ./src/wifi/model/extended-capabilities.d ./src/wifi/model/extended-capabilities.o ./src/wifi/model/frame-capture-model.d ./src/wifi/model/frame-capture-model.o ./src/wifi/model/he-capabilities.d ./src/wifi/model/he-capabilities.o ./src/wifi/model/he-configuration.d ./src/wifi/model/he-configuration.o ./src/wifi/model/he-operation.d ./src/wifi/model/he-operation.o ./src/wifi/model/he-ru.d ./src/wifi/model/he-ru.o ./src/wifi/model/ht-capabilities.d ./src/wifi/model/ht-capabilities.o ./src/wifi/model/ht-configuration.d ./src/wifi/model/ht-configuration.o ./src/wifi/model/ht-operation.d ./src/wifi/model/ht-operation.o ./src/wifi/model/ideal-wifi-manager.d ./src/wifi/model/ideal-wifi-manager.o ./src/wifi/model/infrastructure-wifi-mac.d ./src/wifi/model/infrastructure-wifi-mac.o ./src/wifi/model/interference-helper.d ./src/wifi/model/interference-helper.o ./src/wifi/model/mac-low-transmission-parameters.d ./src/wifi/model/mac-low-transmission-parameters.o ./src/wifi/model/mac-low.d ./src/wifi/model/mac-low.o ./src/wifi/model/mac-rx-middle.d ./src/wifi/model/mac-rx-middle.o ./src/wifi/model/mac-tx-middle.d ./src/wifi/model/mac-tx-middle.o ./src/wifi/model/mgt-headers.d ./src/wifi/model/mgt-headers.o ./src/wifi/model/minstrel-ht-wifi-manager.d ./src/wifi/model/minstrel-ht-wifi-manager.o ./src/wifi/model/minstrel-wifi-manager.d ./src/wifi/model/minstrel-wifi-manager.o ./src/wifi/model/mpdu-aggregator.d ./src/wifi/model/mpdu-aggregator.o ./src/wifi/model/msdu-aggregator.d ./src/wifi/model/msdu-aggregator.o ./src/wifi/model/nist-error-rate-model.d ./src/wifi/model/nist-error-rate-model.o ./src/wifi/model/obss-pd-algorithm.d ./src/wifi/model/obss-pd-algorithm.o ./src/wifi/model/onoe-wifi-manager.d ./src/wifi/model/onoe-wifi-manager.o ./src/wifi/model/originator-block-ack-agreement.d ./src/wifi/model/originator-block-ack-agreement.o ./src/wifi/model/parf-wifi-manager.d ./src/wifi/model/parf-wifi-manager.o ./src/wifi/model/preamble-detection-model.d ./src/wifi/model/preamble-detection-model.o ./src/wifi/model/qos-blocked-destinations.d ./src/wifi/model/qos-blocked-destinations.o ./src/wifi/model/qos-txop.d ./src/wifi/model/qos-txop.o ./src/wifi/model/qos-utils.d ./src/wifi/model/qos-utils.o ./src/wifi/model/regular-wifi-mac.d ./src/wifi/model/regular-wifi-mac.o ./src/wifi/model/rraa-wifi-manager.d ./src/wifi/model/rraa-wifi-manager.o ./src/wifi/model/rrpaa-wifi-manager.d ./src/wifi/model/rrpaa-wifi-manager.o ./src/wifi/model/simple-frame-capture-model.d ./src/wifi/model/simple-frame-capture-model.o ./src/wifi/model/snr-tag.d ./src/wifi/model/snr-tag.o ./src/wifi/model/spectrum-wifi-phy.d ./src/wifi/model/spectrum-wifi-phy.o ./src/wifi/model/ssid.d ./src/wifi/model/ssid.o ./src/wifi/model/sta-wifi-mac.d ./src/wifi/model/sta-wifi-mac.o ./src/wifi/model/status-code.d ./src/wifi/model/status-code.o ./src/wifi/model/supported-rates.d ./src/wifi/model/supported-rates.o ./src/wifi/model/table-based-error-rate-model.d ./src/wifi/model/table-based-error-rate-model.o ./src/wifi/model/threshold-preamble-detection-model.d ./src/wifi/model/threshold-preamble-detection-model.o ./src/wifi/model/txop.d ./src/wifi/model/txop.o ./src/wifi/model/vht-capabilities.d ./src/wifi/model/vht-capabilities.o ./src/wifi/model/vht-configuration.d ./src/wifi/model/vht-configuration.o ./src/wifi/model/vht-operation.d ./src/wifi/model/vht-operation.o ./src/wifi/model/wifi-ack-policy-selector.d ./src/wifi/model/wifi-ack-policy-selector.o ./src/wifi/model/wifi-information-element-vector.d ./src/wifi/model/wifi-information-element-vector.o ./src/wifi/model/wifi-information-element.d ./src/wifi/model/wifi-information-element.o ./src/wifi/model/wifi-mac-header.d ./src/wifi/model/wifi-mac-header.o ./src/wifi/model/wifi-mac-queue-item.d ./src/wifi/model/wifi-mac-queue-item.o ./src/wifi/model/wifi-mac-queue.d ./src/wifi/model/wifi-mac-queue.o ./src/wifi/model/wifi-mac-trailer.d
	-$(RM) ./src/wifi/model/wifi-mac-trailer.o ./src/wifi/model/wifi-mac.d ./src/wifi/model/wifi-mac.o ./src/wifi/model/wifi-mode.d ./src/wifi/model/wifi-mode.o ./src/wifi/model/wifi-net-device.d ./src/wifi/model/wifi-net-device.o ./src/wifi/model/wifi-phy-header.d ./src/wifi/model/wifi-phy-header.o ./src/wifi/model/wifi-phy-state-helper.d ./src/wifi/model/wifi-phy-state-helper.o ./src/wifi/model/wifi-phy-tag.d ./src/wifi/model/wifi-phy-tag.o ./src/wifi/model/wifi-phy.d ./src/wifi/model/wifi-phy.o ./src/wifi/model/wifi-ppdu.d ./src/wifi/model/wifi-ppdu.o ./src/wifi/model/wifi-psdu.d ./src/wifi/model/wifi-psdu.o ./src/wifi/model/wifi-radio-energy-model.d ./src/wifi/model/wifi-radio-energy-model.o ./src/wifi/model/wifi-remote-station-info.d ./src/wifi/model/wifi-remote-station-info.o ./src/wifi/model/wifi-remote-station-manager.d ./src/wifi/model/wifi-remote-station-manager.o ./src/wifi/model/wifi-spectrum-phy-interface.d ./src/wifi/model/wifi-spectrum-phy-interface.o ./src/wifi/model/wifi-spectrum-signal-parameters.d ./src/wifi/model/wifi-spectrum-signal-parameters.o ./src/wifi/model/wifi-tx-current-model.d ./src/wifi/model/wifi-tx-current-model.o ./src/wifi/model/wifi-tx-vector.d ./src/wifi/model/wifi-tx-vector.o ./src/wifi/model/wifi-utils.d ./src/wifi/model/wifi-utils.o ./src/wifi/model/yans-error-rate-model.d ./src/wifi/model/yans-error-rate-model.o ./src/wifi/model/yans-wifi-channel.d ./src/wifi/model/yans-wifi-channel.o ./src/wifi/model/yans-wifi-phy.d ./src/wifi/model/yans-wifi-phy.o

.PHONY: clean-src-2f-wifi-2f-model

